apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: monitoring
  
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: docker.io/cars213/servidor_hub:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: "1.2"
            memory: "3Gi"
          requests:
            cpu: "0.9"
            memory: "2Gi"
        ports:
        - containerPort: 1935
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: monitoring
spec:
  selector:
    app: nginx
  type: NodePort
  ports:
  - protocol: TCP
    port: 1935           # Puerto que expone el servicio dentro del clúster
    targetPort: 1935     # Puerto que utiliza el contenedor
    nodePort: 31935      # Puerto en los nodos (puedes asignarlo automáticamente si no especificas)
