apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
   
  
    global:
      scrape_interval: 15s
   
    scrape_configs:
    
      - job_name: 'prometheus'
        static_configs:
          - targets: ['prometheus-service.monitoring.svc.cluster.local:9090']
        relabel_configs:
          - source_labels: ['__address__']
            action: replace
            target_label: instance

      - job_name: 'grafana'
        static_configs:
          - targets: ['grafana-service.monitoring.svc.cluster.local:3000']
        relabel_configs:
          - source_labels: ['__address__']
            action: replace
            target_label: instance

      - job_name: 'cadvisor'
        static_configs:
          - targets: ['cadvisor-service.monitoring.svc.cluster.local:8080']
        relabel_configs:
          - source_labels: ['__address__']
            action: replace
            target_label: instance

      - job_name: 'node_exporter'
        static_configs:
          - targets: ['node-exporter-service.monitoring.svc.cluster.local:9100']
        relabel_configs:
          - source_labels: ['__address__']
            action: replace
            target_label: instance

      - job_name: 'server'
        static_configs:
          - targets: ['nginx-service.monitoring.svc.cluster.local:1935']
        relabel_configs:
          - source_labels: ['__address__']
            action: replace
            target_label: instance
            
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-deployment
  namespace: monitoring
  labels:
    app: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:v2.28.1
          imagePullPolicy: IfNotPresent
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus/"
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-config-volume
              mountPath: /etc/prometheus/
            - name: prometheus-storage-volume
              mountPath: /prometheus
      volumes:
        - name: prometheus-config-volume
          configMap:
            name: prometheus-config
        - name: prometheus-storage-volume
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: monitoring
  labels:
    app: prometheus
spec:
  type: NodePort
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: 30909
  selector:
    app: prometheus
